version: '3.1'
services:
    postgres:
        image: postgres:11
        ports:
            - '${PG_PORT}:5432'
        environment:
            - POSTGRES_DB=${PG_NAME}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASS}
        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        image: redis:5.0.9
        ports:
            - '${REDIS_PORT}:6379'

    rc:
        image: rediscommander/redis-commander:latest
        ports:
            - '8081:8081'
        environment:
            - REDIS_HOSTS=redis
        depends_on:
            - redis

    medcreds-api:
        build: .
        ports:
            - '${API_PORT}:5000'
        depends_on:
            - redis
            - postgres

volumes:
    db-data:
