module.exports = {
  User: require('./user.model'),
  Organization: require('./organization.model'),
  Event: require('./event.model'),
  Test: require('./test.model'),
  TestState: require('./test-state.model'),
  Meeting: require('./meeting.model'),
  Role: require('./role.model'),
  Callback: require('./callbacks.model'),
  Wallet: require('./wallet.model'),
  Lead: require('./lead.model'),
  Verification: require('./verification.model'),
  OrgConnections: require('./organizations-connections.model'),
  AgencyConnection: require('./agency-connection.model'),
  AgencyCredential: require('./agency-credential.model'),
  AgencyVerification: require('./agency-verification.model'),
  WalletConnection: require('./wallet-connection.model'),
  WalletCredential: require('./wallet-credential.model'),
  WalletVerification: require('./wallet-verification.model')
};
